I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/bus_minigame.rpy", line 369, in script
    label play_bus:
Exception: Could not find return label '_call_play_bus_1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/bus_minigame.rpy", line 369, in script
    label play_bus:
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1782, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\renpy-8.0.3-sdk\renpy\execution.py", line 726, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label '_call_play_bus_1'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Любовь, выпивка, паника, лирика 1.0
Fri Mar 24 15:23:38 2023
