I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2912, in script
    grusha "Ну так иди нахуй отсюда!"
Exception: Sayer 'grusha' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2912, in script
    grusha "Ну так иди нахуй отсюда!"
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'grusha' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Любовь, выпивка, паника, лирика 1.0
Tue Mar 21 00:14:24 2023
